version: '3.8'

networks:
  shared-network:
    driver: bridge

volumes:
  grafana_data: {}

services:
  calc-http:
    container_name: calc_http
    networks:
      - shared-network
    build: .
    command: [ "http" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/debug/liveness" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    ports:
      - "8080:8080" # CRUD API
      - "8081:8081" # DEBUG API
    depends_on:
      - db

  # Run dependencies
  db:
    container_name: calc_db
    networks:
      - shared-network
    image: postgres:13.4-alpine
    ports:
      - "5433:5432"
    expose:
      - 5433
    environment:
      POSTGRES_ROOT_PASSWORD: calc
      POSTGRES_DATABASE: calc
      POSTGRES_USER: calc
      POSTGRES_PASSWORD: calc

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - shared-network
    ports:
      - "9090:9090"
    command:
      - --config.file=/prometheus.yml
    volumes:
      - ./prometheus.yml:/prometheus.yml:ro
    depends_on:
      - calc-http

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - shared-network
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  wait:
    image: dokku/wait
    networks:
      - shared-network
